services:
    Devolicious\OhDearAppHealthBundle\Controller\HealthController:
        arguments:
            - '@Devolicious\OhDearAppHealthBundle\HealthChecker'
            - '%oh_dear_app_health.secret%'
        public: true
        tags:
            - { name: 'controller.service_arguments' }

    Devolicious\OhDearAppHealthBundle\Command\HealthCheckCommand:
        arguments:
            - '@Devolicious\OhDearAppHealthBundle\HealthChecker'
        tags:
            - { name: 'console.command' }

    Devolicious\OhDearAppHealthBundle\HealthChecker:
        arguments:
            - '@Devolicious\OhDearAppHealthBundle\Store\RequestStore'
            - '%oh_dear_app_health.expiration_threshold%'

    Devolicious\OhDearAppHealthBundle\Store\CachePoolStore:
        arguments:
            - '@cache.app'

    Devolicious\OhDearAppHealthBundle\Store\RequestStore: '@Devolicious\OhDearAppHealthBundle\Store\CachePoolStore'