services:
    Devolicious\OhDearAppHealthBundle\Controller\HealthController:
        arguments:
            - '@Devolicious\OhDearAppHealthBundle\HealthChecker'
        public: true
        tags:
            - { name: 'controller.service_arguments' }

    Devolicious\OhDearAppHealthBundle\Command\HealthCheckCommand:
        arguments:
            - '@Devolicious\OhDearAppHealthBundle\HealthChecker'
        tags:
            - { name: 'console.command' }

    Devolicious\OhDearAppHealthBundle\HealthChecker:
        arguments:
            - '@Devolicious\OhDearAppHealthBundle\Store\RequestStore'

    Devolicious\OhDearAppHealthBundle\Checker\DatabaseChecker:
        arguments:
            - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: 'oh_dear_app_health.checker' }

    Devolicious\OhDearAppHealthBundle\Store\CachePoolStore:
        arguments:
            - '@cache.app'

    Devolicious\OhDearAppHealthBundle\Store\RequestStore: '@Devolicious\OhDearAppHealthBundle\Store\CachePoolStore'